name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Library (SDK) workflow
  library:
    name: SDK Library
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint and format check (SDK)
        run: yarn workspace @virginmediao2/storyblok-sdk check:fix

      - name: Build SDK
        run: yarn workspace @virginmediao2/storyblok-sdk build

      - name: Upload SDK build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk-build
          path: sdk/dist/
          retention-days: 7

  # Documentation app workflow
  docs:
    name: Documentation App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate SDK documentation
        run: yarn workspace @virginmediao2/storyblok-sdk docs

      - name: Lint and format check (Docs)
        run: yarn workspace docs check:fix

      - name: Build docs app
        run: yarn workspace docs build

      - name: Upload docs build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/out/
          retention-days: 7

  # Deploy to GitHub Pages (main branch only)
  deploy-docs:
    name: Deploy Documentation
    needs: [library, docs]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate SDK documentation
        run: yarn workspace @virginmediao2/storyblok-sdk docs

      - name: Build docs app
        run: yarn workspace docs build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



