name: SDK Library CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'sdk/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'sdk/**'
      - 'package.json'
      - 'yarn.lock'

jobs:
  library:
    name: SDK Library
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack
        run: corepack enable

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn/cache
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint and format check
        run: yarn workspace @virginmediao2/storyblok-sdk check:fix

      - name: Type check
        run: yarn workspace @virginmediao2/storyblok-sdk type-check

      - name: Run tests
        run: yarn workspace @virginmediao2/storyblok-sdk test

      - name: Build SDK
        run: yarn workspace @virginmediao2/storyblok-sdk build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sdk-build-${{ github.sha }}
          path: sdk/dist/
          retention-days: 30


